name: my b11 app
on: push

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:

      - name: checkout to repo 
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: check node js version 
        run: node --version 

      
      - name: install dependencies 
        run: npm install

      - name: testing the application
        run: npm test 
      
