name: my b11 app
on: push

jobs:
  testing: 
    runs-on: ubuntu-latest
    steps:

      - name: checkout to repo 
        uses: actions/checkout@v4 

      - name: list files from directory 
        uses: |
              ls -la 
              cat README.md
      
      
